manifest:
  projects:
    - name: zmk
      path: zmk
      url: __VENDOR_ZMK_URL__
      revision: vendor
      import:
        path: app/west.yml
        name-blocklist:
          - zmk-studio-messages
  self:
    path: config
